version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - SECRET_KEY=4gd*q-knfb4_qs%wf)ryfndq0x4l9&#4$i)h+amtr4!k6+r7qm
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  db:
    image: postgres:10
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data

volumes:
    db:
