# Generated by Django 2.2.1 on 2019-05-17 21:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('field_type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Date'), (3, 'Choice')])),
                ('is_required', models.BooleanField(default=False)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_fields', to='risk.RiskType')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.RiskType')),
            ],
        ),
    ]
